from enum import Enum


DATA_START = 0xFF
F = 0.5

class Register(Enum):
    MODEL_NUMBER_L = 0
    MODEL_NUMBER_H = 1
    VERSION_OF_FIRMWARE = 2
    ID = 3
    BAUD_RATE = 4
    RETURN_DELAY_TIME = 5
    CW_ANGLE_LIMIT_L = 6
    CW_ANGLE_LIMIT_H = 7
    CCW_ANGLE_LIMIT_L = 8
    CCW_ANGLE_LIMIT_H = 9
    HIGHEST_LIMIT_TEMPERATURE = 11
    LOWEST_LIMIT_VOLTAGE = 12
    HIGHEST_LIMIT_VOLTAGE = 13
    MAX_TORQUE_L = 14
    MAX_TORQUE_H = 15
    STATUS_RETURN_LEVEL = 16
    ALARM_LED = 17
    ALARM_SHUTDOWN = 18
    TORQUE_ENABLE = 24
    LED = 25
    CW_COMPLIANCE_MARGIN = 26
    CCW_COMPLIANCE_MARGIN = 27
    CW_COMPLIANCE_SLOPE = 28
    CCW_COMPLIANCE_SLOPE = 29
    GOAL_POSITION_L = 30
    GOAL_POSITION_H = 31
    MOVING_SPEED_L = 32
    MOVING_SPEED_H = 33
    TORQUE_LIMIT_L = 34
    TORQUE_LIMIT_H = 35
    PRESENT_POSITION_L = 36
    PRESENT_POSITION_H = 37
    PRESENT_SPEED_L = 38
    PRESENT_SPEED_H = 39
    PRESENT_LOAD_L = 40
    PRESENT_LOAD_H = 41
    PRESENT_VOLTAGE = 42
    PRESENT_TEMPERATURE = 43
    REGISTERED = 44
    MOVING = 46
    LOCK = 47
    PUNCH_L = 48
    PUNCH_H = 49

class Instructions(Enum):
    PING = 1
    READ = 2
    WRITE = 3
    REG_WRITE = 4
    ACTION = 5
    FACTORY_RESET = 6
    REBOOT = 8
    SYNC_WRITE = 131
    BULK_READ = 146
    
class Error(Enum):
    NO_ERROR = 0x00
    INSTRUCTION_ERROR = 0x40
    OVERLOAD_ERROR = 0x20
    CHECKSUM_ERROR = 0x10
    RANGE_ERROR = 0x08
    OVERHEATING_ERROR = 0x04
    ANGLE_LIMIT_ERROR = 0x02
    INPUT_VOLTAGE_ERROR = 0x01